Repository masnannstudent/be-ruti_store, pull requests merged in 2024-01, with the labels that each got.

#1 feature: login user
  .gitignore
  go.mod
  go.sum
  main.go
  module/entities/users.go
  module/feature/auth/domain/interface.go
  module/feature/auth/domain/request.go
  module/feature/auth/domain/response.go
  module/feature/auth/handler/handler.go
  module/feature/auth/mocks/AuthHandlerInterface.go
  module/feature/auth/mocks/AuthRepositoryInterface.go
  module/feature/auth/mocks/AuthServiceInterface.go
  module/feature/auth/modules.go
  module/feature/auth/repository/repository.go
  module/feature/auth/service/service.go
  module/feature/auth/service/service_test.go
  module/feature/middleware/auth.go
  module/feature/middleware/logger.go
  module/feature/middleware/middleware.go
  module/feature/route/route.go
  utils/database/migrate.go
  utils/database/postgres.go
  utils/hash/interface.go
  utils/hash/password.go
  utils/mocks/ConfigInterface.go
  utils/mocks/HashInterface.go
  utils/mocks/JWTInterface.go
  utils/response/response.go
  utils/token/jwt.go
  utils/validator/validate.go
  utils/viper/viper.go
Labels: enhancement

#2 feature: deploy project
  .gitignore
  main.go
  utils/database/postgres.go
  utils/viper/viper.go
Labels: enhancement

#3 bugfix: deployment
  config/config.go
  go.mod
  go.sum
  main.go
  module/feature/auth/domain/interface.go
  module/feature/auth/domain/response.go
  module/feature/auth/handler/handler.go
  module/feature/auth/modules.go
  module/feature/auth/repository/repository.go
  module/feature/auth/service/service.go
  module/feature/middleware/auth.go
  module/feature/route/route.go
  utils/database/migrate.go
  utils/database/postgres.go
  utils/token/jwt.go
  utils/viper/viper.go
Labels: bug

#4 bugfix: deployment
  config/config.go
  go.mod
  go.sum
  main.go
  module/feature/auth/domain/interface.go
  module/feature/auth/domain/response.go
  module/feature/auth/handler/handler.go
  module/feature/auth/modules.go
  module/feature/auth/repository/repository.go
  module/feature/auth/service/service.go
  module/feature/middleware/auth.go
  module/feature/route/route.go
  utils/database/migrate.go
  utils/database/postgres.go
  utils/token/jwt.go
  utils/viper/viper.go
Labels: bug

#5 feature: register user
  module/feature/auth/domain/interface.go
  module/feature/auth/domain/request.go
  module/feature/auth/domain/response.go
  module/feature/auth/handler/handler.go
  module/feature/auth/modules.go
  module/feature/auth/repository/repository.go
  module/feature/auth/service/service.go
  module/feature/auth/service/service_test.go
  module/feature/mocks/AuthHandlerInterface.go
  module/feature/mocks/AuthRepositoryInterface.go
  module/feature/mocks/AuthServiceInterface.go
  utils/mocks/ConfigInterface.go
  utils/mocks/JWTInterface.go
Labels: enhancement

#6 feature: register user
  module/feature/auth/domain/interface.go
  module/feature/auth/domain/request.go
  module/feature/auth/domain/response.go
  module/feature/auth/handler/handler.go
  module/feature/auth/modules.go
  module/feature/auth/repository/repository.go
  module/feature/auth/service/service.go
  module/feature/auth/service/service_test.go
  module/feature/mocks/AuthHandlerInterface.go
  module/feature/mocks/AuthRepositoryInterface.go
  module/feature/mocks/AuthServiceInterface.go
  utils/mocks/ConfigInterface.go
  utils/mocks/JWTInterface.go
Labels: enhancement

#7 feature: get all product
  module/entities/product.go
  module/feature/auth/mocks/AuthHandlerInterface.go
  module/feature/auth/mocks/AuthRepositoryInterface.go
  module/feature/auth/mocks/AuthServiceInterface.go
  module/feature/auth/service/service_test.go
  module/feature/product/domain/interface.go
  module/feature/product/domain/response.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/route/route.go
  utils/database/migrate.go
Labels: enhancement

#8 feature: get all order
  module/entities/order.go
  module/entities/product.go
  module/feature/order/domain/interface.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/domain/response.go
  module/feature/product/repository/repository.go
  module/feature/route/route.go
  utils/database/migrate.go
  utils/generator/generator.go
Labels: enhancement

#9 feature: get all order
  module/entities/order.go
  module/entities/product.go
  module/feature/auth/mocks/AuthHandlerInterface.go
  module/feature/auth/mocks/AuthRepositoryInterface.go
  module/feature/auth/mocks/AuthServiceInterface.go
  module/feature/auth/service/service_test.go
  module/feature/order/domain/interface.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/domain/interface.go
  module/feature/product/domain/response.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/route/route.go
  utils/database/migrate.go
  utils/generator/generator.go
Labels: enhancement

#11 feature: get product by id
  config/config.go
  go.mod
  go.sum
  main.go
  module/entities/product.go
  module/feature/address/domain/interface.go
  module/feature/address/repository/repository.go
  module/feature/address/service/service.go
  module/feature/middleware/auth.go
  module/feature/order/domain/interface.go
  module/feature/order/domain/request.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/domain/interface.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/route/route.go
  module/feature/user/domain/interface.go
  module/feature/user/repository/repository.go
  module/feature/user/service/service.go
  utils/payment/midtrans.go
  utils/payment/request.go
  utils/payment/transaction_status.go
  utils/response/response.go
  utils/validator/validate.go
Labels: enhancement

#12 feature: get all address
  module/feature/address/domain/interface.go
  module/feature/address/domain/response.go
  module/feature/address/handler/handler.go
  module/feature/address/modules.go
  module/feature/address/repository/repository.go
  module/feature/address/service/service.go
  module/feature/order/service/service.go
  module/feature/product/domain/interface.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/route/route.go
Labels: enhancement

#13 feature: get all address
  module/feature/address/domain/interface.go
  module/feature/address/domain/response.go
  module/feature/address/handler/handler.go
  module/feature/address/modules.go
  module/feature/address/repository/repository.go
  module/feature/address/service/service.go
  module/feature/order/service/service.go
  module/feature/route/route.go
Labels: enhancement

#14 feature: get all carousel
  config/config.go
  go.mod
  go.sum
  module/entities/carousel.go
  module/feature/home/domain/interface.go
  module/feature/home/domain/request.go
  module/feature/home/domain/response.go
  module/feature/home/handler/handler.go
  module/feature/home/modules.go
  module/feature/home/repository/repository.go
  module/feature/home/service/service.go
  module/feature/route/route.go
  utils/database/migrate.go
  utils/upload/upload.go
Labels: enhancement

#15 feature: create carousels
  config/config.go
  go.mod
  go.sum
  module/entities/carousel.go
  module/feature/home/domain/interface.go
  module/feature/home/domain/request.go
  module/feature/home/domain/response.go
  module/feature/home/handler/handler.go
  module/feature/home/modules.go
  module/feature/home/repository/repository.go
  module/feature/home/service/service.go
  module/feature/route/route.go
  utils/database/migrate.go
  utils/upload/upload.go
Labels: enhancement

#16 feature : dashboard
  module/feature/home/domain/interface.go
  module/feature/home/domain/response.go
  module/feature/home/handler/handler.go
  module/feature/home/modules.go
  module/feature/home/repository/repository.go
  module/feature/home/service/service.go
  module/feature/product/repository/repository.go
Labels: enhancement

#17 feature : dashboard
  module/feature/home/domain/interface.go
  module/feature/home/domain/response.go
  module/feature/home/handler/handler.go
  module/feature/home/modules.go
  module/feature/home/repository/repository.go
  module/feature/home/service/service.go
  module/feature/product/repository/repository.go
Labels: enhancement

#18 feature: get all users
  go.mod
  module/feature/middleware/middleware.go
  module/feature/route/route.go
  module/feature/user/domain/interface.go
  module/feature/user/domain/request.go
  module/feature/user/domain/response.go
  module/feature/user/handler/handler.go
  module/feature/user/modules.go
  module/feature/user/repository/repository.go
  module/feature/user/service/service.go
Labels: enhancement

#19 feature: get all users
  go.mod
  module/feature/middleware/middleware.go
  module/feature/route/route.go
  module/feature/user/domain/interface.go
  module/feature/user/domain/request.go
  module/feature/user/domain/response.go
  module/feature/user/handler/handler.go
  module/feature/user/modules.go
  module/feature/user/repository/repository.go
  module/feature/user/service/service.go
Labels: enhancement

#20 improvement : routing
  config/config.go
  module/feature/address/domain/interface.go
  module/feature/address/domain/request.go
  module/feature/address/domain/response.go
  module/feature/address/handler/handler.go
  module/feature/address/modules.go
  module/feature/address/repository/repository.go
  module/feature/address/service/service.go
  module/feature/home/modules.go
  module/feature/order/modules.go
  module/feature/product/modules.go
  utils/shipping/interface.go
  utils/shipping/rajaongkir.go
  utils/shipping/request.go
Labels: documentation, enhancement

#21 feature : create address
  config/config.go
  module/feature/address/domain/interface.go
  module/feature/address/domain/request.go
  module/feature/address/domain/response.go
  module/feature/address/handler/handler.go
  module/feature/address/modules.go
  module/feature/address/repository/repository.go
  module/feature/address/service/service.go
  module/feature/home/modules.go
  module/feature/order/modules.go
  module/feature/product/modules.go
  utils/shipping/interface.go
  utils/shipping/rajaongkir.go
  utils/shipping/request.go
Labels: enhancement

#22 feature: delete category
  module/entities/category.go
  module/entities/product.go
  module/feature/category/domain/interface.go
  module/feature/category/domain/request.go
  module/feature/category/domain/response.go
  module/feature/category/handler/handler.go
  module/feature/category/modules.go
  module/feature/category/repository/repostory.go
  module/feature/category/service/service.go
  module/feature/home/modules.go
  module/feature/route/route.go
  utils/database/migrate.go
Labels: enhancement

#23 feature: delete product
  module/entities/category.go
  module/entities/product.go
  module/feature/category/repository/repostory.go
  module/feature/order/modules.go
  module/feature/product/domain/interface.go
  module/feature/product/domain/request.go
  module/feature/product/domain/response.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/route/route.go
Labels: enhancement

#25 feature: create reviews
  module/entities/review.go
  module/feature/category/handler/handler.go
  module/feature/product/domain/interface.go
  module/feature/product/domain/response.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/review/domain/interface.go
  module/feature/review/domain/request.go
  module/feature/review/domain/response.go
  module/feature/review/handler/handler.go
  module/feature/review/modules.go
  module/feature/review/repository/repository.go
  module/feature/review/service/service.go
  module/feature/route/route.go
  utils/database/migrate.go
Labels: enhancement

#26 feature : update and delete article
  module/entities/article.go
  module/feature/article/domain/interface.go
  module/feature/article/domain/request.go
  module/feature/article/domain/response.go
  module/feature/article/handler/handler.go
  module/feature/article/modules.go
  module/feature/article/repository/repository.go
  module/feature/article/service/service.go
  module/feature/route/route.go
  utils/database/migrate.go
Labels: enhancement

#28 improvement: get all user
  module/feature/user/domain/response.go
Labels: enhancement

#29 feature: update product photo
  module/entities/product.go
  module/feature/product/domain/interface.go
  module/feature/product/domain/request.go
  module/feature/product/domain/response.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/review/repository/repository.go
Labels: enhancement

#30 improvement: reduce stock when order
  module/feature/order/service/service.go
  module/feature/product/domain/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
Labels: enhancement

#31 improvement: reduce stock when order
  module/entities/product.go
  module/feature/order/service/service.go
  module/feature/product/domain/interface.go
  module/feature/product/domain/request.go
  module/feature/product/domain/response.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/review/repository/repository.go
  module/feature/user/domain/response.go
Labels: enhancement

#32 feature: get notification user
  module/entities/notification.go
  module/feature/notification/domain/interface.go
  module/feature/notification/domain/request.go
  module/feature/notification/domain/response.go
  module/feature/notification/handler/handler.go
  module/feature/notification/modules.go
  module/feature/notification/repository/repository.go
  module/feature/notification/service/service.go
  module/feature/order/domain/request.go
  module/feature/order/modules.go
  module/feature/order/service/service.go
  module/feature/route/route.go
  utils/database/migrate.go
Labels: enhancement

#34 feature: create order by cart
  module/entities/cart.go
  module/entities/notification.go
  module/feature/notification/domain/interface.go
  module/feature/notification/domain/request.go
  module/feature/notification/domain/response.go
  module/feature/notification/handler/handler.go
  module/feature/notification/modules.go
  module/feature/notification/repository/repository.go
  module/feature/notification/service/service.go
  module/feature/order/domain/interface.go
  module/feature/order/domain/request.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/route/route.go
  utils/database/migrate.go
Labels: enhancement

#35 feature: get order by id
  module/feature/order/domain/interface.go
  module/feature/order/domain/request.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
Labels: enhancement

#36 feature: get user by id
  module/feature/order/domain/interface.go
  module/feature/order/domain/request.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
Labels: enhancement

#37 feature: get product recomendation
  config/config.go
  go.mod
  go.sum
  module/feature/order/modules.go
  module/feature/product/domain/interface.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/review/modules.go
  utils/assitant/interface.go
  utils/assitant/openai.go
Labels: enhancement

#38 feature: get all order user
  config/config.go
  go.mod
  go.sum
  module/feature/order/domain/interface.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/domain/interface.go
  module/feature/product/handler/handler.go
  module/feature/product/modules.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/review/modules.go
  utils/assitant/interface.go
  utils/assitant/openai.go
Labels: enhancement

#39 feature: get all order user
  module/feature/order/domain/interface.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
Labels: enhancement

#40 feature: get latest transaction
  module/feature/home/domain/interface.go
  module/feature/home/domain/response.go
  module/feature/home/handler/handler.go
  module/feature/home/modules.go
  module/feature/home/repository/repository.go
  module/feature/home/service/service.go
  module/feature/order/service/service.go
  module/feature/product/repository/repository.go
Labels: enhancement

#41 feature: get latest transaction
  module/feature/home/domain/interface.go
  module/feature/home/domain/response.go
  module/feature/home/handler/handler.go
  module/feature/home/modules.go
  module/feature/home/repository/repository.go
  module/feature/home/service/service.go
  module/feature/order/service/service.go
  module/feature/product/repository/repository.go
Labels: enhancement

#42 improvement: delete cart when order by cart
  module/feature/order/domain/interface.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
Labels: enhancement

#43 improvement: order with size and add gender user
  module/entities/cart.go
  module/entities/order.go
  module/entities/product.go
  module/entities/users.go
  module/feature/order/domain/request.go
  module/feature/order/domain/response.go
  module/feature/order/service/service.go
  module/feature/product/domain/request.go
  module/feature/product/domain/response.go
  module/feature/product/service/service.go
  module/feature/user/domain/request.go
  module/feature/user/domain/response.go
  module/feature/user/service/service.go
Labels: enhancement

#44 improvement: order with size and add gender user
  module/entities/cart.go
  module/entities/order.go
  module/entities/product.go
  module/entities/users.go
  module/feature/order/domain/interface.go
  module/feature/order/domain/request.go
  module/feature/order/domain/response.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/domain/request.go
  module/feature/product/domain/response.go
  module/feature/product/service/service.go
  module/feature/user/domain/request.go
  module/feature/user/domain/response.go
  module/feature/user/service/service.go
Labels: enhancement

#45 feature: get cart by id
  module/feature/order/domain/interface.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
Labels: enhancement

#46 improvement: search on product
  module/feature/product/domain/interface.go
  module/feature/product/handler/handler.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
Labels: enhancement

#47 improvement: search on product
  module/feature/order/domain/interface.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/domain/interface.go
  module/feature/product/handler/handler.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
Labels: enhancement

#48 feature: search on get all order and payment
  module/feature/order/domain/interface.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
Labels: enhancement

#49 testing: address testing
  module/feature/address/domain/interface.go
  module/feature/address/domain/request.go
  module/feature/address/handler/handler.go
  module/feature/address/mocks/AddressHandlerInterface.go
  module/feature/address/mocks/AddressRepositoryInterface.go
  module/feature/address/mocks/AddressServiceInterface.go
  module/feature/address/modules.go
  module/feature/address/repository/repository.go
  module/feature/address/service/service.go
  module/feature/address/service/service_test.go
Labels: enhancement

#50 testing: address testing
  module/feature/address/domain/interface.go
  module/feature/address/domain/request.go
  module/feature/address/handler/handler.go
  module/feature/address/mocks/AddressHandlerInterface.go
  module/feature/address/mocks/AddressRepositoryInterface.go
  module/feature/address/mocks/AddressServiceInterface.go
  module/feature/address/modules.go
  module/feature/address/repository/repository.go
  module/feature/address/service/service.go
  module/feature/address/service/service_test.go
  module/feature/order/domain/interface.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
Labels: enhancement

#51 feature: review product
  module/entities/order.go
  module/entities/review.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/service/service.go
  module/feature/review/domain/interface.go
  module/feature/review/domain/request.go
  module/feature/review/repository/repository.go
  module/feature/review/service/service.go
Labels: enhancement

#52 feature: chatbot
  main.go
  module/feature/order/modules.go
  module/feature/user/domain/interface.go
  module/feature/user/domain/request.go
  module/feature/user/handler/handler.go
  module/feature/user/modules.go
  module/feature/user/repository/repository.go
  module/feature/user/service/service.go
Labels: enhancement

#53 feature: chatbot
  main.go
  module/entities/order.go
  module/entities/review.go
  module/feature/order/domain/response.go
  module/feature/order/handler/handler.go
  module/feature/order/modules.go
  module/feature/order/service/service.go
  module/feature/review/domain/interface.go
  module/feature/review/domain/request.go
  module/feature/review/repository/repository.go
  module/feature/review/service/service.go
  module/feature/user/domain/interface.go
  module/feature/user/domain/request.go
  module/feature/user/handler/handler.go
  module/feature/user/modules.go
  module/feature/user/repository/repository.go
  module/feature/user/service/service.go
Labels: enhancement

#54 improvement: color product
  module/entities/product.go
  module/feature/product/domain/request.go
  module/feature/product/domain/response.go
  module/feature/product/service/service.go
  module/feature/review/domain/response.go
  module/feature/review/handler/handler.go
Labels: enhancement
